language: go
arch:
  - AMD64
  - ppc64le
go:
  - 1.13.x
  - tip
sudo: false
cache:
  directories:
    - vendor
    - _internal_bin/$(go version | awk '{ print $NF }')
script:
  - make test
  - make all
